# -*- coding: utf-8 -*-
"""Tarefa2-Telemed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPId-HL6b6oGWYnSrkboTqHM3E2jteSt
"""

import torch

def funcao_mse(valor_real, valor_previsto):
  return(torch.mean(torch.square(valor_previsto - valor_real)))


y_real = torch.tensor([1.0, 2.0, 3.0])
y_previsto = torch.tensor([1.5, 2.3, 3.7])

print("O valor revelado pela loss function foi: %f" % (funcao_mse(y_real, y_previsto)))

import torch

def cross_entropy_loss(y_probabilidades, y_real):
  probabilidades_corretas = y_probabilidades[range(len(y_probabilidades)), y_real]

  return -torch.log(probabilidades_corretas).mean()


y_real = torch.tensor([0, 2])
y_probabilidades = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])

print("O valor revelado pela loss function foi: %f" % (cross_entropy_loss(y_probabilidades, y_real)))